service: prospectplusagent

runtime: python311

entrypoint: uvicorn prospectplusagent.main:app --host 0.0.0.0 --port $PORT

env_variables:
  ENVIRONMENT: production
  
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
